version: '2'

services:
  mongo:
    image: 'mongo:3.4.4'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  browserquest:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: Dockerfile
    command: node server.js -p 80
    ports:
      - '80:80'
    volumes:
      - './assets:/usr/src/app/assets'
      - './js:/usr/src/app/js'
      - './server.js:/usr/src/app/server.js'
      - './package.json:/usr/src/app/package.json'
      - './index.html:/usr/src/app/index.html'
volumes:
  mongo: